services:
  # STACK
  postgres:
    image: pgvector/pgvector:pg17
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - workley
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
  ollama:
    image: docker.io/ollama/ollama:0.12.9
    tty: true
    ports:
      - "7869:11434"
    restart: "no"
    volumes:
      - ./ollama/ollama:/root/.ollama
    networks:
      - workley
    pull_policy: always
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0
  ollama-webui:
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - "8080:8080"
    restart: "no"
    volumes:
      - ./ollama/ollama-webui:/app/backend/data
    networks:
      - workley
    depends_on:
      - ollama
    environment: # https://docs.openwebui.com/getting-started/env-configuration#default_models
      - ENV=dev
      - WEBUI_AUTH=False
      - WEBUI_NAME=Workley AI
      - WEBUI_URL=http://localhost:8080
      - WEBUI_SECRET_KEY=t0p-s3cr3t
      - OLLAMA_BASE_URLS=http://host.docker.internal:7869 #comma separated ollama hosts
    extra_hosts:
      - host.docker.internal:host-gateway
  # APP
  workley-app:
    image: node:24-slim
    working_dir: /app
    command: sh -c "npm install && npx ng serve --host 0.0.0.0 --proxy-config proxy.docker.config.json --configuration development"
    ports:
      - "4200:4200"
    volumes:
      - ../workley-app:/app
      - /app/node_modules
    networks:
      - workley
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: "no"
volumes:
  ollama_data:
  postgres_data:
networks:
  workley:
    driver: bridge